### ISSUE TITLE
Feature proposal - inline help

### ISSUE THREAD

**Issue by MCGallaspy** [learningequality/ka-lite#3407]
[External link](https://docs.google.com/document/d/11wY1EViZrCKXZkus-7Pf4RMCbEYuaTNSCRa5YCglMMU/edit?usp=sharing)
**Feature Name**: Inline Help

**Team members**: 
Teresa Do
Mike Gallaspy (mentor)

**PR reviewer**: Richard or Aron or Jamie? (TBD)

**Description**:
	An inline help system for app pages. Teresa is taking the lead on this, with Mike serving as a mentor. Weekly joint hacking time will be scheduled. The components are:

* An API endpoint that serves inline-help data (which we’re referring to as intros) determined by a url  passed to it. Takes in YAML and spits out serialized JSON.
* A YAML file which defines intros based off our specification (see below), and which is keyed by a regex against which urls are matched.
* An injector script in the base template that makes an API request, builds an intro in the page using intro.js, and provides an access point for starting the intro (some DOM element).

**Description of intro YAML format**:
Each url pattern has a list of jQuery-style selectors. Modals will be attached to each selector. Each selector has a list of attributes which determine the content and presentation of the modal. Valid attributes include:

* step: An integer. Should be sequential. Required.
* text: The text presented in the modal. Required.
* before-showing: Optional. User actions taken to make an element visible. A list of key-value pairs. Supposed to be extensible, in case we find we need more actions. Valid keys are:
  * click: Clicks an object specified by the value. Value is a jQuery-style selector.
  * scroll-to: An integer. Value is x-position on the page that should be scrolled to.

The specification is in YAML from better human readability, but the API endpoint should parse it into JSON (for easier use in the script).

**Example**:
```YAML
management/zone/\w+/:
  - ul.nav li a.admin-only:
    - step: 1
    - text: Welcome! This is the landing page for admins. If at any point you would like to navigate back to this page, click on this tab!
  - li.facility:
    - step: 2
    - text: Clicking on this tab will show you a quick overview of all facilities and devices
    - before-showing:
        - click: #the-button
        - scroll-to: 400
  - a.create-facility:
    - step: 3
    - text: To add new facilities, click here...
```
**Mockups**:
![admin_general1](https://cloud.githubusercontent.com/assets/8888020/6835275/df0f3a0e-d2f6-11e4-934b-1a7588180bed.png)
![admin_general2](https://cloud.githubusercontent.com/assets/8888020/6835276/e008a526-d2f6-11e4-8f17-3460c392f4f9.png)

**Milestones**:
* April 3, 2015 - Finish writing a stubbed-out script to inject intros into a page
* May 6, 2015 - Write an API endpoint to serve intros
  * April 10 - Write a specification for the endpoint
  * April 17 - Read up on Tastypie a bit
  * May 1 - Implement that endpoint using Tastypie
  * May 6 - Extra debug time & Writing intros
* May 13 - Design and implement entry points for intros (i.e. how to start them)
* May 20 - Finish / extra debug time
